### ISSUE TITLE
Update help page

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/50words.online#13]
From @nthieberger 

The current link to 'Help' should have a screen with the following above the current video:

#Learning resources
Download a set of learning activities to accompany the 50 Words map. These are designed for students of all ages and can be used at home or in the classroom.
Link to: https://arts.unimelb.edu.au/__data/assets/pdf_file/0005/3352838/50_Words-Lockdown-activities.pdf

# Video of how to use the site

**Comment by nthieberger** [comment]
Hi Marco, if possible, can you please make thischange before the end of May? I'm presenting 50 words at a Reconciliation Week event on the 1st and it should get some traffic after that.

**Comment by marcolarosa** [comment]
How's this?

<img width="1087" alt="Screenshot 2023-05-16 at 5 28 15 pm" src="https://github.com/CoEDL/50words.online/assets/2639995/13e8e37c-bf5c-4377-84c5-f52b7a2e71fa">

**Comment by nthieberger** [comment]
yep, good, thanks
