### ISSUE TITLE
Please update google analytics

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/50words.online#14]
Here's the new tag

<script async src="https://www.googletagmanager.com/gtag/js?id=G-XCLN54BQ4P"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XCLN54BQ4P');
</script>

**Comment by marcolarosa** [comment]
Done. The tag was there but it wasn't initialised correctly. The API may have changed.
