### ISSUE TITLE
Please change this link

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/50words.online#17]
In the HELP tab, (https://github.com/CoEDL/50words.online/blob/master/src/components/Help.component.vue), please change 
 https://arts.unimelb.edu.au/__data/assets/pdf_file/0005/3352838/50_Words-Lockdown-activities.pdf.

to this:
 https://arts.unimelb.edu.au/__data/assets/pdf_file/0005/3352838/50Words_A5ActivityBooklet-V3-.pdf

I tried but it is write only for me

**Comment by marcolarosa** [comment]
Done. Please check and close this ticket if ok. Thanks.

**Comment by nthieberger** [comment]
Thanks!
