### ISSUE TITLE
CC licence

### ISSUE THREAD

**Issue by nthieberger** [CoEDL/50words.online#8]
Please add this to the bottom of each screen, just to the left of the three icons:
the logo for this licence and a link to the licence page, and the words "Attribution-NonCommercial 4.0 International"
https://creativecommons.org/licenses/by-nc/4.0/

Also add this to the 'About' screen:
CC logo and link, "The material in this site is made available under a Creative Commons BY-NC licence, you can use it as long as it is non-commercial and the source is attributed."

This is needed as we have heard of a few potential contributors who would feel better about using the site if the licence terms were clearly stated.

**Comment by marcolarosa** [comment]
The red boxes are just on these screenshots. Ok?

<img width="1445" alt="Screen Shot 2022-08-04 at 11 54 50 am" src="https://user-images.githubusercontent.com/2639995/182746412-6e467335-1ab9-43a8-bc43-1ad2605b9f55.png">
<img width="1443" alt="Screen Shot 2022-08-04 at 11 54 46 am" src="https://user-images.githubusercontent.com/2639995/182746755-273eb549-248a-4865-ab0d-02c95f7e5ea0.png">
<img width="378" alt="Screen Shot 2022-08-04 at 11 58 37 am" src="https://user-images.githubusercontent.com/2639995/182746702-47abe533-5079-4f69-8ed9-aa48607a0547.png">
